<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MamuzContactTest\Bootstrap'                               => __DIR__ . '/test/Bootstrap.php',
    'MamuzContactTest\Controller\CommandControllerFactoryTest' =>
    __DIR__ . '/test/MamuzContactTest/Controller/CommandControllerFactoryTest.php',
    'MamuzContactTest\Controller\CommandControllerTest'        =>
    __DIR__ . '/test/MamuzContactTest/Controller/CommandControllerTest.php',
    'MamuzContactTest\Entity\MamuzContactTest'                 =>
    __DIR__ . '/test/MamuzContactTest/Entity/ContactTest.php',
    'MamuzContactTest\Form\CreateFactoryTest'                  =>
    __DIR__ . '/test/MamuzContactTest/Form/CreateFactoryTest.php',
    'MamuzContactTest\Mapper\Db\CommandTest'                   =>
    __DIR__ . '/test/MamuzContactTest/Mapper/Db/CommandTest.php',
    'MamuzContactTest\Service\CommandFactoryTest'              =>
    __DIR__ . '/test/MamuzContactTest/Service/CommandFactoryTest.php',
    'MamuzContactTest\Service\CommandTest'                     =>
    __DIR__ . '/test/MamuzContactTest/Service/CommandTest.php',
    'MamuzContactTest\Service\FactoryTest'                     =>
    __DIR__ . '/test/MamuzContactTest/DomainManager/FactoryTest.php',
    'MamuzContact\Controller\CommandController'                =>
    __DIR__ . '/src/MamuzContact/Controller/CommandController.php',
    'MamuzContact\Controller\CommandControllerFactory'         =>
    __DIR__ . '/src/MamuzContact/Controller/CommandControllerFactory.php',
    'MamuzContact\DomainManager\Factory'                       =>
    __DIR__ . '/src/MamuzContact/DomainManager/Factory.php',
    'MamuzContact\DomainManager\ProviderInterface'             =>
    __DIR__ . '/src/MamuzContact/DomainManager/ProviderInterface.php',
    'MamuzContact\Entity\Contact'                              => __DIR__ . '/src/MamuzContact/Entity/Contact.php',
    'MamuzContact\Feature\CommandInterface'                    =>
    __DIR__ . '/src/MamuzContact/Feature/CommandInterface.php',
    'MamuzContact\Form\CreateFactory'                          => __DIR__ . '/src/MamuzContact/Form/CreateFactory.php',
    'MamuzContact\Mapper\Db\Command'                           => __DIR__ . '/src/MamuzContact/Mapper/Db/Command.php',
    'MamuzContact\Module'                                      => __DIR__ . '/Module.php',
    'MamuzContact\Service\Command'                             => __DIR__ . '/src/MamuzContact/Service/Command.php',
    'MamuzContact\Service\CommandFactory'                      =>
    __DIR__ . '/src/MamuzContact/Service/CommandFactory.php',
);
